name: Understanding of github_sha 
on: [push]
jobs:
    github-sha-example:
        runs-on: ubuntu-sha
        steps:
            - name: printing github_sha
              uses: actions/checkout@v2

            - name: display the commit sha
              run: echo "The commit SHA is $GITHUB_SHA"