name: Matrix1
on: [push]
jobs: 
    node-matrix1:
        continue-on-error: true
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14,15,16]
            max-parallel: 2
        runs-on: ${{matrix.os}}
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}
