name: Run Name Example

#PR #: This is a static string that precedes the pull request number. It helps to format the output clearly, indicating that the 
#number is related to a pull request

run-name: PR #${{github.event.pull_request.number}} by ${{github.actor}}
on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: print hell world
              run: echo "Hello World"