name: Status check function
on: [push]
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: sleep 20
            - name: Runs on failure
              if: failure()
              run: echo "Runs only on failure"
            # This is not needed(Default behavior)
            - name: Runs on success
              if: success()
              run: echo 'Runs on success'
            
            # Always() function will return true.
            - name: Always runs
              # Another way to achieve always functionality using (if: success() || failure())
              if: always()
              run: echo "Always runs"

            - name: Runs when cancelled
              if: cancelled()
              run: echo "run on cancelled"
    job-2:
        runs-on: ubuntu-latest

        # here I am defining dependency using needs keyword. it is saying job-2 is dependent on job-1.
        needs: job-1
        if: failure()
        steps:
            - run: echo "job-2"