name: Variables and Secrets
on: [push]
jobs:
    log-vars:
        runs-on: ${{vars.JOB_RUNNER}}
        env:
            BOOLEAN_SECRET: ${{secrets.BOOLEAN_SECRET}}
            ENV_LEVEL_VAR: ${{vars.ENV_NAME}}
        steps:
            - name: Run only if BOOLEAN SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "Successfully authenticated..."
            - name: Logs vars
              run: |
               echo "${{vars.JOB_RUNNER}}"
               echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
               