name: working directory
on: [push, pull_request, issues]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory and list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REF
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                